FROM public.ecr.aws/docker/library/node:18
WORKDIR /app

# cria um package.json básico e instala dependências
RUN npm init -y \
  && npm install express lodash axios

CMD ["node", "-e", "require('express')()"]